swagger: "2.0"
info:
  description: "Aplikacja do zarządzania zadaniami"
  version: "1.0.0"
  title: "TODO App"
host: "localhost"
basePath: "/todo"
tags:
  - name: "users"
    description: "Operacje związane z użytkownikiem"
  - name: "tasks"
    description: "Operacje związane z zadaniami"
paths:
  /user:
    post:
      tags:
        - "users"
      summary: "Dodaje nowego użytkownika do aplikacji"
      operationId: "createUser"
      consumes:
        - "application/json"
      parameters:
        - name: "user"
          in: "body"
          schema:
            $ref: "#/definitions/User"
      responses:
        "201":
          description: "Użytkownik dodany"
        "409":
          description: "Użytkownik o podanej nazwie już istnieje"
  /task:
    post:
      tags:
        - "tasks"
      summary: "Dodaje nowe zadanie dla użytkownika"
      operationId: "createTask"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "auth"
          in: "header"
          required: true
          type: "string"
          description: "Ciąg znaków 'base64(username):base64(password)', gdzie base64() oznacza funkcję kodującą algorytmem Base64"
        - name: "task"
          in: "body"
          schema:
            $ref: "#/definitions/Task"
      responses:
        "201":
          description: "Zadanie zostało dodane"
          schema:
            $ref: "#/definitions/UUIDResponse"
        "401":
          description: "Brak użytkownika lub błędne hasło"
    get:
      tags:
        - "tasks"
      summary: "Zwraca listę zadań użytkownika"
      operationId: "readTasks"
      produces:
        - "application/json"
      parameters:
        - name: "auth"
          in: "header"
          required: true
          type: "string"
          description: "Ciąg znaków 'base64(username):base64(password)', gdzie base64() oznacza funkcję kodującą algorytmem Base64"
      responses:
        "200":
          description: "Lista zadań"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/TaskItem"
        "401":
          description: "Brak użytkownika lub błędne hasło"
  /task/{id}:
    get:
      tags:
        - "tasks"
      summary: "Zwraca szczegóły wybranego zadania"
      operationId: "readTask"
      produces:
        - "application/json"
      parameters:
        - name: "auth"
          in: "header"
          required: true
          type: "string"
          description: "Ciąg znaków 'base64(username):base64(password)', gdzie base64() oznacza funkcję kodującą algorytmem Base64"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
          description: "Unikalny identyfikator zadania w formacie UUID"
      responses:
        "200":
          description: "Szczegóły zadania"
          schema:
            $ref: "#/definitions/TaskItem"
        "401":
          description: "Brak użytkownika lub błędne hasło"
        "403":
          description: "Zadanie należy do innego użytkownika"
        "404":
          description: "Nie ma takiego zadania"
    put:
      tags:
        - "tasks"
      summary: "Modyfikuje wybrane zadanie"
      operationId: "updateTask"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "auth"
          in: "header"
          required: true
          type: "string"
          description: "Ciąg znaków 'base64(username):base64(password)', gdzie base64() oznacza funkcję kodującą algorytmem Base64"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
          description: "Unikalny identyfikator zadania w formacie UUID"
        - name: "task"
          in: "body"
          schema:
            $ref: "#/definitions/Task"
      responses:
        "200":
          description: "Szczegóły zadania"
          schema:
            $ref: "#/definitions/TaskItem"
        "401":
          description: "Brak użytkownika lub błędne hasło"
        "403":
          description: "Zadanie należy do innego użytkownika"
        "404":
          description: "Nie ma takiego zadania"
    delete:
      tags:
        - "tasks"
      summary: "Usuwa wybrane zadanie"
      operationId: "deleteTask"
      consumes:
        - "application/json"
      parameters:
        - name: "auth"
          in: "header"
          required: true
          type: "string"
          description: "Ciąg znaków 'base64(username):base64(password)', gdzie base64() oznacza funkcję kodującą algorytmem Base64"
        - name: "id"
          in: "path"
          required: true
          type: "string"
          format: "uuid"
          description: "Unikalny identyfikator zadania w formacie UUID"
      responses:
        "200":
          description: "Zadanie usunięte"
        "401":
          description: "Brak użytkownika lub błędne hasło"
        "403":
          description: "Zadanie należy do innego użytkownika"
        "404":
          description: "Nie ma takiego zadania"
definitions:
  User:
    type: "object"
    required:
      - "username"
      - "password"
    properties:
      username:
        type: "string"
        example: "janKowalski"
      password:
        type: "string"
        example: "am!sK#123"
  Task:
    type: "object"
    required:
      - "description"
    properties:
      description:
        type: "string"
        example: "Kup mleko"
      due:
        type: "string"
        format: "date"
        description: "Data w formacie ISO 8601"
        example: "2021-06-30"
  UUIDResponse:
    type: "object"
    required:
      - "id"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "Unikalny identyfikator zadania w formacie UUID"
        example: "237e9877-e79b-12d4-a765-321741963000"
  TaskItem:
    type: "object"
    required:
      - "id"
      - "description"
    properties:
      id:
        type: "string"
        format: "uuid"
        description: "Unikalny identyfikator zadania w formacie UUID"
        example: "237e9877-e79b-12d4-a765-321741963000"
      description:
        type: "string"
        example: "Kup mleko"
      due:
        type: "string"
        format: "date"
        description: "Data w formacie ISO 8601"
        example: "2021-06-30"